- name: Getting data from routers

  hosts: Mikrotik IT-GARANT

  gather_facts: false

  tasks:

    - name: system command

      routeros_command:

        commands: /system routerboard print

      register: system_print

    - name: debug print

      debug: var=system_print.stdout_lines

